// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_frames.sql

package database

import (
	"context"
)

const getFrames = `-- name: GetFrames :many
select id, title, description, created_at, modified_at, user_id, frame_status from frame
`

func (q *Queries) GetFrames(ctx context.Context) ([]Frame, error) {
	rows, err := q.db.QueryContext(ctx, getFrames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frame
	for rows.Next() {
		var i Frame
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.UserID,
			&i.FrameStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
