// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_frame.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFrame = `-- name: GetFrame :one
select id, title, description, created_at, modified_at, user_id, frame_status from frame where id = $1
`

func (q *Queries) GetFrame(ctx context.Context, id uuid.UUID) (Frame, error) {
	row := q.db.QueryRowContext(ctx, getFrame, id)
	var i Frame
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.UserID,
		&i.FrameStatus,
	)
	return i, err
}
