services:
  framer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh
    command: bash -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: framer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


