version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: framer 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
