// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppUser struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           sql.NullString
	Provider       sql.NullString
	ProviderUserID sql.NullString
}

type File struct {
	ID         uuid.UUID
	FileName   sql.NullString
	CreatedAt  time.Time
	ModifiedAt time.Time
}

type Frame struct {
	ID          uuid.UUID
	Title       string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	UserID      uuid.UUID
	FrameStatus int16
	ContentType int16
	Content     string
	FileID      uuid.NullUUID
}

type SchemaMigration struct {
	Version string
}
