info:
  contact: {}
paths:
  /api/frame:
    get:
      consumes:
      - application/json
      description: Get Frames for logged in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Frames
  /api/frame/{id}:
    get:
      consumes:
      - application/json
      description: Get Frame by id
      parameters:
      - description: Frame Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Frame
swagger: "2.0"
